[build]
  base    = "client"
  # add --legacy-peer-deps here:
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "client/dist"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
